version: "3.8"

services:
  poll:
    build: ./poll
    ports:
      - "5000:80"
    networks:
      - poll-tier
    environment:
      - PORT=80

  redis:
    image: "redis"
    ports:
      - "6379:6379"
    networks:
      - poll-tier
      - back-tier
    restart: always

  worker:
    build: ./worker
    networks:
      - back-tier

  db:
    image: "postgres"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - result-tier
      - back-tier
    restart: always

  result:
    build: ./result
    ports:
      - "5001:80"
    networks:
      - result-tier
    environment:
      - PORT=80

networks:
  poll-tier:
  result-tier:
  back-tier:

volumes:
  db-data: